# Generated by Django 3.2.4 on 2021-06-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authemail', '0002_emailchangecode'),
        ('ayaloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSignupCode',
            fields=[
                ('signupcode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authemail.signupcode')),
            ],
            options={
                'abstract': False,
            },
            bases=('authemail.signupcode',),
        ),
    ]
