# Generated by Django 3.2.4 on 2021-07-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayaloapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='AccountType',
            field=models.CharField(choices=[('Leesee', 'Leesee'), ('Leeser', 'Leesser')], default='Leeser', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='auth_provider',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
