# Generated by Django 3.2.4 on 2021-06-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayaloapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='AccountType',
            field=models.CharField(choices=[('Leeser', 'Leeser'), ('Leesee', 'Leessee')], max_length=256),
        ),
    ]
