# Generated by Django 3.2.4 on 2021-06-24 09:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayaloapp', '0002_alter_myuser_accounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cool_name',
            field=models.CharField(max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='Username'),
        ),
    ]
