# Generated by Django 3.2.4 on 2021-07-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlisting_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of product'),
        ),
    ]
