# Generated by Django 3.2.4 on 2021-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlisting_api', '0004_alter_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
