# Generated by Django 3.2.4 on 2021-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlisting_api', '0005_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pictureUpload',
            field=models.ImageField(default='null', max_length=255, upload_to='', verbose_name='Picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(max_length=255),
        ),
    ]
